services:
  ipapm:
    build:
      dockerfile: ./dockerfile
    container_name: ipapm
    env_file:
      - path: .env
      - path: .env.local
    environment:
      GO_ENV: development
    healthcheck:
      test:
        - CMD
        - /usr/local/bin/readyz
    network_mode: host
    volumes:
      - ./volumes/ipapm/:/home/nonroot/.config/ipapm/
      - /usr/share/keyrings/:/usr/share/keyrings/:ro
