package apt_test

import (
	"reflect"
	"strings"
	"testing"

	"github.com/NatoBoram/ipapm/apt"
)

const inReleaseExample = `-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: code stable
Label: code stable
Suite: stable
Codename: stable
Date: Fri, 31 Jul 2026 19:19:17 +0000
Architectures: amd64 arm64 armhf all
Components: main
Description: Generated by aptly
Acquire-By-Hash: yes
SHA256:
 73f2795d305962241290af80e9fee41c03257dca8953f4bb03d8be43df70cd93           528571 main/binary-amd64/Packages
 04d3b0d0456522a7f393dd1bc9707b1cac565176c9a5eeaae8c9f2c7a262bb5d            26674 main/binary-amd64/Packages.gz
 4e1911f982647c41b9835b4e9fc24ace026c651338a8562d8469c49a23c49d54           540487 main/binary-arm64/Packages
 8a81ce4bbe6f6c1c953d1e1fefdff18e58bb0e194c85e8d96255903107df2514            26698 main/binary-arm64/Packages.gz
 9a142f6c7bbfdd1a5443fc01a9272c36708439e1552bbd882f6cbc11cb47bdf7           553805 main/binary-armhf/Packages
 2a17775b21e89d7679b2984a65a05c80d1f2899b59eed94c3158f0aece13d1d6            26768 main/binary-armhf/Packages.gz
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                0 main/binary-all/Packages
 6a6e13e68c5fd14fcf3a2bd973609ad6d0e98c9c3bf983db4477e6448a9f68ba               29 main/binary-all/Packages.gz
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                0 main/source/Sources
 f8047b717a8fde71b44b315d78eb8ec5428607d2e292359ff666a781b93bbac1               28 main/source/Sources.gz
SHA512:
 2c0bd02f5fc9ac0fe364e7cf1bf0bb8081a8168a4f85888575b758b5be1237bd53228730c6ca5960d339691ce0bf2e3f30dfccec3e2221e559872d480075814a           528571 main/binary-amd64/Packages
 a5aca12748687fe5f87985a16ec639bc98e07a434f7418819ad8efc53f2a651e2aa1464c50c41c04d9a8278c4c79c2ce71f99838c212985ac51c406e74919136            26674 main/binary-amd64/Packages.gz
 5c4ea2dec89b3e0e5a4b225b649d61882bb597499c0d3138b64254446c41dc24b20214b0dfa1b0a02fdd5fe5f3950b4e4216cfcdf7587476909c1a1ad591689c           540487 main/binary-arm64/Packages
 3705ec0fc8f515f9e9bc2a10c1a3bce1a2e65b852e2521427c8a4e159c04bed66bcc07bed5890d09034a10788e37c36a98122c470595be178d815664043dedbc            26698 main/binary-arm64/Packages.gz
 86eca1f9bbc516d73d59528500cab3e10a62ee9a1d2eec2e23393a08f51f0ad28e028289361c4077a7708980326bdd0f70402027271d61131d3c3be5e732c31c           553805 main/binary-armhf/Packages
 7370e90c1fbc24ec1554e036ea1042226d8553a86b13fbccd826ec64ad89cf70a6ca13a148c1bf85078f6ae9c3f5a5c222ba29e59a6945118906c54f8bbfa2ee            26768 main/binary-armhf/Packages.gz
 cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e                0 main/binary-all/Packages
 07f812e5ddd86ff868dcd998e486dd56c9369077cd6fbbb79dcd3da4014a70e6f46eb867cd36da75e6f43811e85a5af685582e0089e9cb7816957a83d8ce7e10               29 main/binary-all/Packages.gz
 cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e                0 main/source/Sources
 94dfd3dad6fb09c8e95b8c9e0189bab9a62c81da9a97d2b4d8c2b04e2ec2ff97ced059ea9979befcf240bdb65937a6f810b27602a9c65a3e712df720c9a9b946               28 main/source/Sources.gz

-----BEGIN PGP SIGNATURE-----
Version: BSN Pgp v1.0.0.0

iQEcBAEBCAAGBQJqbPVNAAoJEOs+lK2+EinP+9wH/0Fa8ff4BbnK54Kq2MAwtXHt
/ABgXyIhmS9BSfnbrhq+R4C32EMHPF3q3p/97mSUCrmAVzaemhIAOUL4m5vDrh6C
PPwPqiwbnTh7T6SEfAR1botfcGwcD/XFq4D8JPWTe5m9Tgojqm3XGEExen0pQGXC
DCIgez3RCCBSKzZ2cJoBzxpGiGTOTLqXh300SoIpcu+br+gu9JyGOJt2SQErGGne
+T81Ed85pDAzh+kcuuNS/CO0kxJaBW4vijwyrsULL6bOjh2QowI1IjWduU+WcnxS
uUDyYKbb1kiZ4wIwkDnUhARBJWKWd7sZ2ebb42J9dqUaoP/6p5rEYZflEGUbfl8=
-----END PGP SIGNATURE-----
`

func TestParseInRelease(t *testing.T) {
	inRelease, err := apt.ParseInRelease(strings.NewReader(inReleaseExample))
	if err != nil {
		t.Fatalf("ParseInRelease failed: %v", err)
	}

	expected := apt.InRelease{
		Hash:          "SHA256",
		Origin:        "code stable",
		Label:         "code stable",
		Suite:         "stable",
		Codename:      "stable",
		Date:          "Fri, 31 Jul 2026 19:19:17 +0000",
		Architectures: []string{"amd64", "arm64", "armhf", "all"},
		Components:    []string{"main"},
		Description:   "Generated by aptly",
		AcquireByHash: "yes",
		MD5Sum:        []apt.InReleaseSum{},
		SHA1:          []apt.InReleaseSum{},
		SHA256: []apt.InReleaseSum{
			{Hash: "73f2795d305962241290af80e9fee41c03257dca8953f4bb03d8be43df70cd93", Size: 528571, Path: "main/binary-amd64/Packages"},
			{Hash: "04d3b0d0456522a7f393dd1bc9707b1cac565176c9a5eeaae8c9f2c7a262bb5d", Size: 26674, Path: "main/binary-amd64/Packages.gz"},
			{Hash: "4e1911f982647c41b9835b4e9fc24ace026c651338a8562d8469c49a23c49d54", Size: 540487, Path: "main/binary-arm64/Packages"},
			{Hash: "8a81ce4bbe6f6c1c953d1e1fefdff18e58bb0e194c85e8d96255903107df2514", Size: 26698, Path: "main/binary-arm64/Packages.gz"},
			{Hash: "9a142f6c7bbfdd1a5443fc01a9272c36708439e1552bbd882f6cbc11cb47bdf7", Size: 553805, Path: "main/binary-armhf/Packages"},
			{Hash: "2a17775b21e89d7679b2984a65a05c80d1f2899b59eed94c3158f0aece13d1d6", Size: 26768, Path: "main/binary-armhf/Packages.gz"},
			{Hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", Size: 0, Path: "main/binary-all/Packages"},
			{Hash: "6a6e13e68c5fd14fcf3a2bd973609ad6d0e98c9c3bf983db4477e6448a9f68ba", Size: 29, Path: "main/binary-all/Packages.gz"},
			{Hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", Size: 0, Path: "main/source/Sources"},
			{Hash: "f8047b717a8fde71b44b315d78eb8ec5428607d2e292359ff666a781b93bbac1", Size: 28, Path: "main/source/Sources.gz"},
		},
		SHA512: []apt.InReleaseSum{
			{Hash: "2c0bd02f5fc9ac0fe364e7cf1bf0bb8081a8168a4f85888575b758b5be1237bd53228730c6ca5960d339691ce0bf2e3f30dfccec3e2221e559872d480075814a", Size: 528571, Path: "main/binary-amd64/Packages"},
			{Hash: "a5aca12748687fe5f87985a16ec639bc98e07a434f7418819ad8efc53f2a651e2aa1464c50c41c04d9a8278c4c79c2ce71f99838c212985ac51c406e74919136", Size: 26674, Path: "main/binary-amd64/Packages.gz"},
			{Hash: "5c4ea2dec89b3e0e5a4b225b649d61882bb597499c0d3138b64254446c41dc24b20214b0dfa1b0a02fdd5fe5f3950b4e4216cfcdf7587476909c1a1ad591689c", Size: 540487, Path: "main/binary-arm64/Packages"},
			{Hash: "3705ec0fc8f515f9e9bc2a10c1a3bce1a2e65b852e2521427c8a4e159c04bed66bcc07bed5890d09034a10788e37c36a98122c470595be178d815664043dedbc", Size: 26698, Path: "main/binary-arm64/Packages.gz"},
			{Hash: "86eca1f9bbc516d73d59528500cab3e10a62ee9a1d2eec2e23393a08f51f0ad28e028289361c4077a7708980326bdd0f70402027271d61131d3c3be5e732c31c", Size: 553805, Path: "main/binary-armhf/Packages"},
			{Hash: "7370e90c1fbc24ec1554e036ea1042226d8553a86b13fbccd826ec64ad89cf70a6ca13a148c1bf85078f6ae9c3f5a5c222ba29e59a6945118906c54f8bbfa2ee", Size: 26768, Path: "main/binary-armhf/Packages.gz"},
			{Hash: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e", Size: 0, Path: "main/binary-all/Packages"},
			{Hash: "07f812e5ddd86ff868dcd998e486dd56c9369077cd6fbbb79dcd3da4014a70e6f46eb867cd36da75e6f43811e85a5af685582e0089e9cb7816957a83d8ce7e10", Size: 29, Path: "main/binary-all/Packages.gz"},
			{Hash: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e", Size: 0, Path: "main/source/Sources"},
			{Hash: "94dfd3dad6fb09c8e95b8c9e0189bab9a62c81da9a97d2b4d8c2b04e2ec2ff97ced059ea9979befcf240bdb65937a6f810b27602a9c65a3e712df720c9a9b946", Size: 28, Path: "main/source/Sources.gz"},
		},
		Raw:      []byte(inReleaseExample),
		Warnings: []error{},
	}

	// Field-by-field
	if eq := reflect.DeepEqual(inRelease.Hash, expected.Hash); !eq {
		t.Errorf("Expected %v, got %v", expected.Hash, inRelease.Hash)
	}
	if eq := reflect.DeepEqual(inRelease.Origin, expected.Origin); !eq {
		t.Errorf("Expected %v, got %v", expected.Origin, inRelease.Origin)
	}
	if eq := reflect.DeepEqual(inRelease.Label, expected.Label); !eq {
		t.Errorf("Expected %v, got %v", expected.Label, inRelease.Label)
	}
	if eq := reflect.DeepEqual(inRelease.Suite, expected.Suite); !eq {
		t.Errorf("Expected %v, got %v", expected.Suite, inRelease.Suite)
	}
	if eq := reflect.DeepEqual(inRelease.Codename, expected.Codename); !eq {
		t.Errorf("Expected %v, got %v", expected.Codename, inRelease.Codename)
	}
	if eq := reflect.DeepEqual(inRelease.Date, expected.Date); !eq {
		t.Errorf("Expected %v, got %v", expected.Date, inRelease.Date)
	}
	if eq := reflect.DeepEqual(inRelease.Architectures, expected.Architectures); !eq {
		t.Errorf("Expected %v, got %v", expected.Architectures, inRelease.Architectures)
	}
	if eq := reflect.DeepEqual(inRelease.Components, expected.Components); !eq {
		t.Errorf("Expected %v, got %v", expected.Components, inRelease.Components)
	}
	if eq := reflect.DeepEqual(inRelease.Description, expected.Description); !eq {
		t.Errorf("Expected %v, got %v", expected.Description, inRelease.Description)
	}
	if eq := reflect.DeepEqual(inRelease.AcquireByHash, expected.AcquireByHash); !eq {
		t.Errorf("Expected %v, got %v", expected.AcquireByHash, inRelease.AcquireByHash)
	}
	if eq := reflect.DeepEqual(inRelease.MD5Sum, expected.MD5Sum); !eq {
		t.Errorf("Expected %v, got %v", expected.MD5Sum, inRelease.MD5Sum)
	}
	if eq := reflect.DeepEqual(inRelease.SHA1, expected.SHA1); !eq {
		t.Errorf("Expected %v, got %v", expected.SHA1, inRelease.SHA1)
	}
	if eq := reflect.DeepEqual(inRelease.SHA256, expected.SHA256); !eq {
		t.Errorf("Expected %v, got %v", expected.SHA256, inRelease.SHA256)
	}
	if eq := reflect.DeepEqual(inRelease.SHA512, expected.SHA512); !eq {
		t.Errorf("Expected %v, got %v", expected.SHA512, inRelease.SHA512)
	}
	if eq := reflect.DeepEqual(inRelease.Warnings, expected.Warnings); !eq {
		t.Errorf("Expected %v, got %v", expected.Warnings, inRelease.Warnings)
	}

	if t.Failed() {
		return
	}

	if eq := reflect.DeepEqual(inRelease, expected); !eq {
		t.Errorf("Expected %v, got %v", expected, inRelease)
	}
}
