name: Go

on:
  merge_group:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - run: make build
      - run: make test

      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
